# Generated by Django 4.2.23 on 2025-07-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField()),
                ('altura', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
