# Generated by Django 4.2.23 on 2025-07-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio_facil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('real', models.DecimalField(decimal_places=5, default=1.0, max_digits=10)),
                ('euro', models.DecimalField(decimal_places=5, max_digits=10)),
                ('dolar', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
